### ISSUE TITLE
NIKSS unable to load

### ISSUE THREAD

**Issue by g83wang** [NIKSS-vSwitch/nikss#101]
Hello, I built the https://github.com/p4lang/p4c/blob/main/backends/ebpf/psa/examples/upf.p4
and am trying to load the out.o file with nikss-ctl pipeline load id 0 out.o, which gives me the following error messages:

libbpf: elf: skipping unrecognized data section(9) .maps.clone_session_tbl_inner
libbpf: elf: skipping unrecognized data section(10) .maps.clone_session_tbl
libbpf: elf: skipping unrecognized data section(11) .maps.multicast_grp_tbl_inner
libbpf: elf: skipping unrecognized data section(12) .maps.multicast_grp_tbl
libbpf: elf: skipping unrecognized data section(13) .maps.ingress_ip_forward_ipv4_lpm
libbpf: elf: skipping unrecognized data section(14) .maps.ingress_ip_forward_ipv4_lpm_defaultAction
libbpf: elf: skipping unrecognized data section(15) .maps.ingress_upf_ingress_far_lookup
libbpf: elf: skipping unrecognized data section(16) .maps.ingress_upf_ingress_far_lookup_defaultAction
libbpf: elf: skipping unrecognized data section(17) .maps.ingress_upf_ingress_pdr_lookup_prefixes
libbpf: elf: skipping unrecognized data section(18) .maps.ingress_upf_ingress_pdr_lookup_tuple
libbpf: elf: skipping unrecognized data section(19) .maps.ingress_upf_ingress_pdr_lookup_tuples_map
libbpf: elf: skipping unrecognized data section(20) .maps.ingress_upf_ingress_pdr_lookup_defaultAction
libbpf: elf: skipping unrecognized data section(21) .maps.ingress_upf_ingress_session_lookup_by_teid
libbpf: elf: skipping unrecognized data section(22) .maps.ingress_upf_ingress_session_lookup_by_teid_defaultAction
libbpf: elf: skipping unrecognized data section(23) .maps.ingress_upf_ingress_session_lookup_by_ue_ip
libbpf: elf: skipping unrecognized data section(24) .maps.ingress_upf_ingress_session_lookup_by_ue_ip_defaultAction
libbpf: elf: skipping unrecognized data section(25) .maps.ingress_upf_ingress_source_interface_lookup_by_port
libbpf: elf: skipping unrecognized data section(26) .maps.ingress_upf_ingress_source_interface_lookup_by_port_defaultAction
libbpf: elf: skipping unrecognized data section(27) .maps.ingress_upf_process_ingress_l4port_ingress_l4_dst_port
libbpf: elf: skipping unrecognized data section(28) .maps.ingress_upf_process_ingress_l4port_ingress_l4_dst_port_defaultAction
libbpf: elf: skipping unrecognized data section(29) .maps.ingress_upf_process_ingress_l4port_ingress_l4_src_port
libbpf: elf: skipping unrecognized data section(30) .maps.ingress_upf_process_ingress_l4port_ingress_l4_src_port_defaultAction
libbpf: elf: skipping unrecognized data section(31) .maps.ingress_upf_process_ingress_l4port_ingress_l4port_fields
libbpf: elf: skipping unrecognized data section(32) .maps.ingress_upf_process_ingress_l4port_ingress_l4port_fields_defaultAction
libbpf: elf: skipping unrecognized data section(33) .maps.hdr_md_cpumap
libbpf: elf: skipping unrecognized data section(34) .maps.crc_lookup_tbl
libbpf: elf: skipping unrecognized data section(35) .rodata.cst32
libbpf: elf: skipping unrecognized data section(37) .rodata.cst16
libbpf: elf: skipping unrecognized data section(51) .eh_frame
libbpf: elf: skipping relo section(52) .rel.eh_frame for section(51) .eh_frame
libbpf: maps section in out.o: "clone_session_tbl" has unrecognized, non-zero options
cannot load the BPF program: No such file or directory
An error occurred during pipeline load id 0

The file out.o is in the current directory and it has correct permissions.
Could I get some ideas about what is going wrong here?

Thank you.

**Comment by tatry** [comment]
Hello, thanks for your issue.

To help to reproduce the problem, could you provide following information:
1. Operating system you use (name and version).
2. Kernel and clang version (alternatively you can provide output from command `nikss-ctl validate-os` if you use latest version).

**Comment by g83wang** [comment]
> Hello, thanks for your issue.
> 
> To help to reproduce the problem, could you provide following information:
> 
> 1. Operating system you use (name and version).
> 2. Kernel and clang version (alternatively you can provide output from command `nikss-ctl validate-os` if you use latest version).

Thanks for the reply. 

1. I am using Ubuntu 20.04
2. The kernel version is 5.14.0-1054-oem and the clang version is clang version 10.0.0-4ubuntu

**Comment by tatry** [comment]
I've just run that kernel on my Ubuntu 20.04 machine and I didn't experience the problem with loading.

How do you compile the P4 code?

**Comment by g83wang** [comment]
> I've just run that kernel on my Ubuntu 20.04 machine and I didn't experience the problem with loading.
> 
> How do you compile the P4 code?

Thank you so much for your reply.

I compile it as:

`g83wang@g83wang-ThinkPad-P15s-Gen-2i:~/p4c/backends/ebpf/psa/examples$ p4c-ebpf --arch psa --target kernel -o out.c upf.p4
Setting XDP2TC 'meta' mode by default for TC-based hook.
g83wang@g83wang-ThinkPad-P15s-Gen-2i:~/p4c/backends/ebpf/psa/examples$ clang -Ibackends/ebpf/runtime -Ibackends/ebpf/runtime/usr/include -O2 -g -c -emit-llvm -o out.bc out.c
out.c:445:41: warning: incompatible pointer types assigning to 'u32 *' (aka 'unsigned int *') from 'const u8 *' (aka 'const unsigned char *') [-Wincompatible-pointer-types]
            if (data_size == 8) current = data + 4;
                                        ^ ~~~~~~~~
1 warning generated.
g83wang@g83wang-ThinkPad-P15s-Gen-2i:~/p4c/backends/ebpf/psa/examples$ llc -march=bpf -mcpu=generic -filetype=obj -o out.o out.bc
`

**Comment by g83wang** [comment]
Oh, I see. Thank you.
